#!/usr/bin/python3
import requests
import sys
def send_to_telegram(message):

    apiToken = 'you telegram bot token'
    chatID = 'your chat id for send alert'
    apiURL = f'https://api.telegram.org/bot{apiToken}/sendMessage'

    try:
        response = requests. post(apiURL, json={'chat_id': chatID, 'text': message})
        print(response.text)
    except Exception as e:
        print(e)

send_to_telegram(sys.argv[1])
